# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: coding-challenge-cities-suggestions

provider:
  name: aws
  runtime: nodejs12.x

functions:
  suggestions:
    handler: functions/suggestions.getSuggestions
    events:
      - http:
          path: suggestions
          method: get

custom:
  serverless-offline:
    httpPort: 3000
    lambdaPort: 3002

plugins:
  - serverless-offline
  - serverless-jest-plugin