# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: coding-challenge-cities-autocomplete

provider:
  name: aws
  runtime: nodejs12.x

functions:
  suggestions:
    handler: functions/autocomplate.autocompleteSuggestions
    events:
      - http:
          path: autocomplete
          method: get

custom:
  serverless-offline:
    httpPort: 5000        

plugins:
  - serverless-offline
  - serverless-jest-plugin