# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: coding-challenge-cities-score

provider:
  name: aws
  runtime: nodejs12.x

functions:
  suggestions:
    handler: functions/score.scoreSuggestions
    events:
      - http:
          path: score
          method: post

custom:
  serverless-offline:
    httpPort: 4000
    lambdaPort: 4002

plugins:
  - serverless-offline
  - serverless-jest-plugin